# Generated by Django 2.0 on 2018-08-09 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0006_auto_20180808_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='CommentItem',
        ),
    ]
