- name: Check that the /usr/bin/python3.6 exists
  stat:
    path: /usr/bin/python3.6
  tags: python
  register: python_result

- name: Update apt-cache
  apt: update_cache=yes
  tags: packages, python
  when: python_result.stat.exists == False

- name: Install packages needed for installing Python
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: install python3.6
  become: yes
  apt:
    name: python3.6
    update_cache: yes

- name: install common packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - vim
  - nginx
  - postgresql
  - postgresql-contrib
  - virtualenv
  - python3-pip
  - python3-psycopg2

- name: Install packages for production enviroment
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - nginx

- name: copy nginx config
  become: yes
  template: src=nginx.j2 dest=/etc/nginx/sites-available/tele.conf
  notify:
  - restart nginx

- name: create symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/tele.conf
    dest: /etc/nginx/sites-enabled/default
    state: link


- name: configure systemd for application
  become: yes
  template: src=teleplata.service.j2 dest=/etc/systemd/system/teleplata.service
  notify:
  - restart teleplata.service