version: "3.1"
services:
  web:
    build: .
    command: python ./server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    image: postgres:10.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=adminblog
      - POSTGRES_PASSWORD=adminblog
      - POSTGRES_DB=adminblog
