version: "3.1"
services:
  web:
    container_name: web_dev
    build:
      context: .
      dockerfile: Dockerfile
    # относительно контейнера
    working_dir: /source/server
    entrypoint: bash entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=blog.settings.dev
      - POSTGRES_HOST=database
    volumes:
      - .:/source
    ports:
      - 8000:8000
    depends_on:
      - database
  database:
    container_name: database_dev
    image: postgres:10.1-alpine
    # only for local development
    environment:
      - POSTGRES_USER=adminblog
      - POSTGRES_PASSWORD=adminblog
      - POSTGRES_DB=adminblog
      - POSTGRES_HOST=database
