- name: Creating a user named {{ USERNAME }} on the specified web server (Debian).
  become: yes
  user:
    name: "{{ USERNAME }}"
    password: "{{ hashed_password }}"
    state: present
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/blog


- name: Copy key
  become: yes
  copy:
    src: ~/.ssh/blog.pub
    dest: /home/{{ USERNAME }}/.ssh/authorized_keys
    mode: 0600
    owner: "{{ USERNAME }}"
    group: "{{ USERNAME }}"
  tags:
  - copy_host_ssh_id

- name: Add new user to sudoers list
  become: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ USERNAME }} ALL"
    line: "{{ USERNAME }}	ALL=(ALL) 	NOPASSWD: ALL"
    state: present