- name: clone repository
  git:
    repo: '{{ REPO_URL }}'
    dest: '{{ PROJECT_DIR }}'
    depth: 1
    update: no

- name: Check that the /usr/bin/python3.6 exists
  stat:
    path: /usr/bin/python3.6
  tags: python
  register: python_result

- name: Update apt-cache
  apt: update_cache=yes
  tags: packages, python
  when: python_result.stat.exists == False

- name: Install packages needed for installing Python
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: install python3.6
  become: yes
  apt:
    name: python3.6
    update_cache: yes

- name: install common packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - vim
  - nginx
  - postgresql
  - postgresql-contrib
  - virtualenv
  - python3-pip
  - python3-psycopg2

- name: Install the gpg key for nodejs LTS
  become: yes
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_8.x trusty main"
    state: present
    update_cache: yes

- name: Install the nodejs
  become: yes
  apt:
    name: nodejs
    state: present

- name: install pip requirements
  pip:
    requirements: "{{ PROJECT_DIR }}/requirements.txt"
    virtualenv: "{{ ENV_PATH }}"
    virtualenv_python: python3.6