- name: clone repository
  git:
    repo: '{{ REPO_URL }}'
    dest: '{{ PROJECT_DIR }}'
    depth: 1
    update: no

- name: install pip requirements
  pip:
    requirements: "{{ PROJECT_DIR }}/requirements.txt"
    virtualenv: "{{ ENV_PATH }}"
    virtualenv_python: python3.6