# Generated by Django 2.0.2 on 2018-02-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180216_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Author'),
            preserve_default=False,
        ),
    ]
