# Generated by Django 2.0.2 on 2018-02-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180216_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
